defmodule Tunez.Repo.Migrations.MakeArtistNameUnique do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:artists, [:id], name: "artists_id_index")

    create unique_index(:artists, [:name], name: "artists_name_index")
  end

  def down do
    drop_if_exists unique_index(:artists, [:name], name: "artists_name_index")

    drop_if_exists unique_index(:artists, [:id], name: "artists_id_index")
  end
end
